### ISSUE TITLE
Fix Jacoco version for proper coverage report

### ISSUE THREAD

**Issue by medwardson** [swent-group10/polyfit#154]
JaCoCo was refusing to upload coverage for one of the tests, causing the SonarCloud to say that the file has 0% line coverage.

**Comment by aprilslis** [comment]
It was discovered that the issue comes from an error says java.lang.IllegalStateException: Line 36 is out of range in the file, on a file that is only 34 lines long. After researching, it was discovered that this is a known issue caused by Jacoco itself. The error occurs because Jacoco generates code for each file to help test the coverages, and then the XML coverage report mistakenly says that the file has more lines than it does, which later causes SonarCloud to be confused and recognize it as an error. Newer versions of Jacoco mostly fix this issue, but in our case, it did not. Thus as a workaround, we are adding comments to make line 36 exist, it then properly updates coverage. Currently, no other fixes worked so that's what we'll have to use for now.
